namespace Toggles
{
    // Holds all data about a particular setting in the mod.
    internal class Toggle
    {
        internal bool active = true;

        string description;

        string translateableLabel;

        internal Toggle(string label)
        {
            Label = label;
        }

        internal Toggle(string label, string group, string root, string patch, string mod = null, string translatableLabel = null, string description = null)
        {
            Label = label;
            TranslatableLabel = translatableLabel;
            Description = description;
            Group = group;
            Root = root;
            Patch = patch;
            Mod = mod;
            //DebugUtil.Log("New Toggle:\nlabel: " + Label + "\ngroup: " + Group + "\nroot: " + Root + "\npatch: " + Patch);
        }

        internal string Description
        {
            // If translateableLabel exists this toggle was autogenerated, in which case I have no manually created translation. Print nothing.
            get => description ?? (translateableLabel != null ? null : Label + "Desc");

            set => description = value;
        }

        internal string Group { get; set; }
        internal string Root { get; set; }
        internal string Label { get; private set; }
        internal string Patch { get; set; }
        internal string Mod { get; set; }

        internal string TranslatableLabel
        {
            get => StringUtil.Pretty(translateableLabel);

            set => translateableLabel = value;
        }
    }
}